webtalk_init -webtalk_dir C:\\Users\\HH\\Documents\\Embedded_system\\hust_efi\\fpga\\hust_efi\\hust_efi.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-07-05 19:38:41" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212357014_0_0_323" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tuhb30nccj0mgfdhn8l4glh7kh" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.177 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1657024601719" -context "sdk\\\\bsp/1657024601719"
webtalk_add_data -client sdk -key hwid -value "1656419093599" -context "sdk\\\\bsp/1657024601719"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\bsp/1657024601719"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1657024601719"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1657024601719"
webtalk_add_data -client sdk -key uid -value "1657024611751" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key hwid -value "1656419093599" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key bspid -value "1657024601719" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key projSize -value "362.796875" -context "sdk\\\\application/1657024611751"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1657024721520"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1657024721520"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1657024721520"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1657024721520"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1657024721520"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1657024721520"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1657024721520"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1657024721520"
webtalk_transmit -clientid 2762950019 -regid "212357014_0_0_323" -xml C:\\Users\\HH\\Documents\\Embedded_system\\hust_efi\\fpga\\hust_efi\\hust_efi.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\HH\\Documents\\Embedded_system\\hust_efi\\fpga\\hust_efi\\hust_efi.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\HH\\Documents\\Embedded_system\\hust_efi\\fpga\\hust_efi\\hust_efi.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
